# This file is generated by gyp; do not edit.


LOCAL_PATH := $(call my-dir)
GYP_CONFIGURATION ?= Debug
GYP_VAR_PREFIX ?=
GYP_HOST_VAR_PREFIX ?=
GYP_HOST_MULTILIB ?=

include $(LOCAL_PATH)/libdehaze_jni.target.mk
include $(LOCAL_PATH)/thirdparty/djinni/support-lib/djinni_jni.target.mk

# "gyp_all_modules" is a concatenation of the "gyp_all_modules" targets from
# all the included sub-makefiles. This is just here to clarify.
gyp_all_modules:
