// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from dehaze.djinni

package com.dehaze;

import java.util.concurrent.atomic.AtomicBoolean;

public abstract class Dehaze {
    public abstract String dehaze(String uri, String media);

    public static native Dehaze create();

    private static final class CppProxy extends Dehaze
    {
        private final long nativeRef;
        private final AtomicBoolean destroyed = new AtomicBoolean(false);

        private CppProxy(long nativeRef)
        {
            if (nativeRef == 0) throw new RuntimeException("nativeRef is zero");
            this.nativeRef = nativeRef;
        }

        private native void nativeDestroy(long nativeRef);
        public void destroy()
        {
            boolean destroyed = this.destroyed.getAndSet(true);
            if (!destroyed) nativeDestroy(this.nativeRef);
        }
        protected void finalize() throws java.lang.Throwable
        {
            destroy();
            super.finalize();
        }

        @Override
        public String dehaze(String uri, String media)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_dehaze(this.nativeRef, uri, media);
        }
        private native String native_dehaze(long _nativeRef, String uri, String media);
    }
}
