// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from dehaze.djinni

#include "dehaze.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class OCDehaze;

namespace djinni_generated {

class Dehaze
{
public:
    using CppType = std::shared_ptr<::dehaze::Dehaze>;
    using CppOptType = std::shared_ptr<::dehaze::Dehaze>;
    using ObjcType = OCDehaze*;

    using Boxed = Dehaze;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

