// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from dehaze.djinni

#import <Foundation/Foundation.h>
@class OCDehaze;


@interface OCDehaze : NSObject

+ (nullable OCDehaze *)create;

- (nonnull NSString *)dehazeImage:(nonnull NSString *)uri;

@end
