// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from dehaze.djinni

#import <Foundation/Foundation.h>
@class OCDehaze;


@interface OCDehaze : NSObject

+ (nullable OCDehaze *)create;

- (nonnull NSString *)dehaze:(nonnull NSString *)uri
                       media:(nonnull NSString *)media;

@end
